spring.application.name=myntra-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/myntra-backend
spring.datasource.username=postgres
spring.datasource.password=saran@12345
spring.jpa.hibernate.ddl-auto=update

